CREATE DATABASE IF NOT EXISTS db_sorgummi;
USE db_sorgummi;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'user') DEFAULT 'user',
    resetToken VARCHAR(255) DEFAULT NULL,
    resetExpires BIGINT DEFAULT NULL,
    avatar VARCHAR(255) DEFAULT '',
    phone VARCHAR(50) DEFAULT '',
    location VARCHAR(255) DEFAULT '',
    bio TEXT DEFAULT NULL,
    points INT DEFAULT 0,
    language VARCHAR(10) DEFAULT 'id',
    dark_mode BOOLEAN DEFAULT TRUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT,
    sessionId VARCHAR(255),
    role ENUM('user', 'model'),
    message TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_gaps (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    occurrences INT DEFAULT 1,
    status ENUM('OPEN', 'RESOLVED') DEFAULT 'OPEN',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS articles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(255) NOT NULL,
    bannerUrl VARCHAR(255) DEFAULT '',
    views INT DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    steps TEXT NOT NULL,
    category VARCHAR(255) NOT NULL,
    views INT DEFAULT 0,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    thumbnailUrl VARCHAR(255) DEFAULT '',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS faqs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    answer TEXT,
    status ENUM('BELUM', 'TERJAWAB') DEFAULT 'BELUM',
    userEmail VARCHAR(255) DEFAULT '',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
